version: '3'
services: 
    acad:
      build: .
      ports:
        - "8000:8000"
      working_dir: "/var/www/html"
      command: "php artisan serve --host 0.0.0.0"
      volumes:
        - ".:/var/www/html"